<?php

declare(strict_types=1);

/**
 * Regenerates the generated part of docs.md (helpers and coverage map) from the source.
 * "Not wrapped yet" lists depend on the PHP version and loaded extensions.
 *
 * Usage: php scripts/api-map.php
 */

use Oophp\Tests\Support\ApiMap;

$autoload = __DIR__ . '/../vendor/autoload.php';
if (!is_file($autoload)) {
    fwrite(STDERR, "Missing vendor/autoload.php. Run `composer install` in the project root first.\n");
    exit(1);
}

require $autoload;

const START_MARKER = '<!-- api-map:start -->';
const END_MARKER = '<!-- api-map:end -->';

$docs = __DIR__ . '/../docs.md';

// Native functions a domain is expected to cover, used for "not wrapped yet".
$standard = array_map('strtolower', array_keys((new ReflectionExtension('standard'))->getFunctions()));
$extension = static fn (string $name): array => extension_loaded($name)
    ? array_map('strtolower', array_keys((new ReflectionExtension($name))->getFunctions()))
    : [];
$internal = get_defined_functions()['internal'];
$families = [
    'Arr' => ['`array_*`', array_filter($internal, static fn (string $f): bool => str_starts_with($f, 'array_'))],
    'Str' => ['`str*`, `substr*` (ext/standard)', array_filter(
        $standard,
        static fn (string $f): bool => preg_match('/^(str|substr)/', $f) === 1 && !str_starts_with($f, 'stream_') && $f !== 'strval',
    )],
    'MbStr' => ['ext/mbstring', $extension('mbstring')],
    'Json' => ['ext/json', $extension('json')],
    'Regex' => ['ext/pcre', $extension('pcre')],
    'Hash' => ['ext/hash, `password_*`, `random_*`', array_merge(
        $extension('hash'),
        array_filter($internal, static fn (string $f): bool => str_starts_with($f, 'password_') || str_starts_with($f, 'random_')),
    )],
    'Url' => ['`*url*` (ext/standard)', array_filter($standard, static fn (string $f): bool => str_contains($f, 'url'))],
    'Stream' => ['`stream_*`', array_filter($internal, static fn (string $f): bool => str_starts_with($f, 'stream_'))],
    'Proc' => ['`proc_*`', array_filter($internal, static fn (string $f): bool => str_starts_with($f, 'proc_'))],
    // Procedural aliases of DateTime*, DateTimeZone and DateInterval methods are covered by Date helpers and DateChain.
    'Date' => ['ext/date without `DateTime*` method aliases', array_filter(
        $extension('date'),
        static fn (string $f): bool => preg_match(
            '/^(date_(add|create.*|date_set|diff|format|get_last_errors|interval_.+|isodate_set|modify|offset_get|sub|time_set|timestamp_.+|timezone_.+)|timezone_(?!name_from_abbr$|version_get$).+)$/',
            $f,
        ) !== 1,
    )],
];

$methods = ApiMap::methods();
$chainOf = array_flip(ApiMap::CHAIN_DOMAINS);

// Domain => native => ['static' => method, 'chain' => method].
$rows = [];
$helpers = [];

foreach ($methods as $entry) {
    if ($entry['helper']) {
        $helpers[$entry['class']][] = $entry;

        continue;
    }

    $native = $entry['natives'][0];
    $isStatic = $entry['domain'] === $entry['class'];
    $domain = $entry['domain'];

    // MixedChain methods belong to the domain that wraps the same native statically (jsonEncode → Json).
    if ($domain === null) {
        foreach ($methods as $candidate) {
            if ($candidate['domain'] === $candidate['class'] && $candidate['natives'] === [$native]) {
                $domain = $candidate['domain'];
            }
        }
    }

    $rows[$domain ?? 'Other'][$native][$isStatic ? 'static' : 'chain'] = $entry['method'];
}

$domains = array_values(array_unique(array_map(static fn (array $entry): ?string => $entry['domain'], $methods)));
$domains = array_values(array_filter($domains, static fn (?string $domain): bool => $domain !== null && class_exists('Oophp\\' . $domain)));
sort($domains);

$out = [];
$out[] = START_MARKER;
$out[] = '';
$out[] = sprintf('_Generated by `php scripts/api-map.php` on PHP %d.%d. Do not edit this part by hand._', PHP_MAJOR_VERSION, PHP_MINOR_VERSION);
$out[] = '';
$out[] = '## Helpers';
$out[] = '';
$out[] = 'Methods with behavior of their own: they do not map 1:1 to a native function and are exempt from the naming rule.';
$out[] = 'The list is closed. A new helper is added deliberately to `ApiMap::HELPERS`, then this map is regenerated.';
$out[] = '';
$out[] = '| Class | Helpers |';
$out[] = '| --- | --- |';
foreach ($helpers as $class => $entries) {
    $names = array_map(
        static fn (array $entry): string => '`' . $entry['method'] . '`' . ($entry['natives'] === [] ? '' : ' (' . implode(', ', $entry['natives']) . ')'),
        $entries,
    );
    $out[] = "| `{$class}` | " . implode(', ', $names) . ' |';
}

$summary = [];
$sections = [];
$allWrapped = [];

foreach ($domains as $domain) {
    $natives = $rows[$domain] ?? [];
    ksort($natives);
    $allWrapped += $natives;

    $chain = $chainOf[$domain] ?? null;
    $staticCount = count(array_filter($natives, static fn (array $row): bool => isset($row['static'])));
    $chainCount = count(array_filter($natives, static fn (array $row): bool => isset($row['chain'])));
    $helperCount = count($helpers[$domain] ?? []) + ($chain === null ? 0 : count($helpers[$chain] ?? []));

    [$familyLabel, $family] = $families[$domain] ?? [null, []];
    // Deprecated functions are not candidates for wrapping.
    $family = array_values(array_unique(array_filter(
        $family,
        static fn (string $f): bool => !(new ReflectionFunction($f))->isDeprecated(),
    )));
    $universe = array_unique(array_merge($family, array_keys($natives)));
    $missing = array_values(array_diff($family, array_keys($natives)));
    sort($missing);

    $summary[] = sprintf(
        '| [`%s`](#%s) | %d | %s | %d | %s | %s |',
        $domain,
        strtolower($domain),
        $staticCount,
        $chain === null ? '—' : "{$chainCount} (`{$chain}`)",
        $helperCount,
        $familyLabel ?? '—',
        $familyLabel === null ? '—' : sprintf('%d / %d', count($natives), count($universe)),
    );

    $section = [];
    $section[] = "### {$domain}";
    $section[] = '';
    $section[] = $chain === null ? 'Static only.' : "`{$domain}::of()` → `{$chain}`.";
    $section[] = '';
    $section[] = "| Native | `{$domain}::` | Chain `->` |";
    $section[] = '| --- | --- | --- |';
    foreach ($natives as $native => $row) {
        $section[] = sprintf(
            '| `%s` | %s | %s |',
            $native,
            isset($row['static']) ? '`' . $row['static'] . '`' : '—',
            isset($row['chain']) ? '`' . $row['chain'] . '`' : '—',
        );
    }

    if ($missing !== []) {
        $section[] = '';
        $section[] = sprintf('<details><summary>Not wrapped yet (%d of %s)</summary>', count($missing), $familyLabel);
        $section[] = '';
        $section[] = implode(', ', array_map(static fn (string $f): string => "`{$f}`", $missing));
        $section[] = '';
        $section[] = '</details>';
    }

    $sections[] = implode("\n", $section);
}

$out[] = '';
$out[] = '## Coverage';
$out[] = '';
$out[] = sprintf('%d native functions are wrapped. "Family" is the set of native functions a domain is expected to cover; "Covered" counts wrapped functions against the family plus everything the domain already wraps.', count($allWrapped));
$out[] = '';
$out[] = '| Domain | Static | Chain | Helpers | Family | Covered |';
$out[] = '| --- | --- | --- | --- | --- | --- |';
array_push($out, ...$summary);
$out[] = '';
$out[] = implode("\n\n", $sections);
$out[] = '';
$out[] = END_MARKER;

$content = is_file($docs) ? (string) file_get_contents($docs) : '';
$start = strpos($content, START_MARKER);
$end = strpos($content, END_MARKER);
if ($start === false || $end === false) {
    fwrite(STDERR, 'docs.md must contain ' . START_MARKER . ' and ' . END_MARKER . " markers.\n");
    exit(1);
}

file_put_contents($docs, substr($content, 0, $start) . implode("\n", $out) . substr($content, $end + strlen(END_MARKER)));

echo "docs.md updated.\n";
